name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports: ['5432:5432']
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server
    steps:
      - uses: actions/checkout@master

      - name: Setup Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          bundler: default
          bundler-cache: true

      - name: Setup Node 19
        uses: actions/setup-node@v4
        with:
          node-version: 19.x

      - name: Install dependencies
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          yarn install --frozen-lockfile

      - name: Standardrb Check
        run: bundle exec standardrb

      - name: StandardJs Check
        run: yarn standard

      - name: Brakeman Check
        run: bundle exec brakeman

      - name: Bundler Audit
        run: |
          bundle exec bundle-audit update
          bundle exec bundle-audit check

      - name: Zeitwerk eager load check
        run: bundle exec rails zeitwerk:check

      - name: RSpec
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/test
          REDIS_URL: redis://localhost:6379/0
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          PG_USER: postgres
        run: |
          bin/rails db:test:prepare
          bin/rake
